// <auto-generated />
using System;
using IndekserPrzypraw.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IndekserPrzypraw.Migrations
{
    [DbContext(typeof(SpicesContext))]
    [Migration("20240512194033_IngredientsGramsUintToInt")]
    partial class IngredientsGramsUintToInt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IndekserPrzypraw.Models.Drawer", b =>
                {
                    b.Property<int>("DrawerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DrawerId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DrawerId");

                    b.ToTable("Drawers");
                });

            modelBuilder.Entity("IndekserPrzypraw.Models.Ingredient", b =>
                {
                    b.Property<int>("IngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IngredientId"));

                    b.Property<int>("Grams")
                        .HasColumnType("integer");

                    b.Property<int>("SpiceGroupId")
                        .HasColumnType("integer");

                    b.Property<int?>("SpiceMixRecipeId")
                        .HasColumnType("integer");

                    b.HasKey("IngredientId");

                    b.HasIndex("SpiceGroupId");

                    b.HasIndex("SpiceMixRecipeId");

                    b.ToTable("Ingredient");
                });

            modelBuilder.Entity("IndekserPrzypraw.Models.Spice", b =>
                {
                    b.Property<int>("SpiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SpiceId"));

                    b.Property<DateOnly?>("ExpirationDate")
                        .HasColumnType("date");

                    b.Property<int>("SpiceGroupId")
                        .HasColumnType("integer");

                    b.HasKey("SpiceId");

                    b.HasIndex("SpiceGroupId");

                    b.ToTable("Spices");
                });

            modelBuilder.Entity("IndekserPrzypraw.Models.SpiceGroup", b =>
                {
                    b.Property<int>("SpiceGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SpiceGroupId"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DrawerId")
                        .HasColumnType("integer");

                    b.Property<int>("Grams")
                        .HasColumnType("integer");

                    b.Property<int?>("MinimumCount")
                        .HasColumnType("integer");

                    b.Property<int?>("MinimumGrams")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SpiceGroupId");

                    b.HasIndex("DrawerId");

                    b.ToTable("SpiceGroups");
                });

            modelBuilder.Entity("IndekserPrzypraw.Models.SpiceMixRecipe", b =>
                {
                    b.Property<int>("SpiceMixRecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SpiceMixRecipeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SpiceMixRecipeId");

                    b.ToTable("SpiceMixRecipes");
                });

            modelBuilder.Entity("IndekserPrzypraw.Models.Ingredient", b =>
                {
                    b.HasOne("IndekserPrzypraw.Models.SpiceGroup", "SpiceGroup")
                        .WithMany()
                        .HasForeignKey("SpiceGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IndekserPrzypraw.Models.SpiceMixRecipe", null)
                        .WithMany("Ingredients")
                        .HasForeignKey("SpiceMixRecipeId");

                    b.Navigation("SpiceGroup");
                });

            modelBuilder.Entity("IndekserPrzypraw.Models.Spice", b =>
                {
                    b.HasOne("IndekserPrzypraw.Models.SpiceGroup", "SpiceGroup")
                        .WithMany("Spices")
                        .HasForeignKey("SpiceGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SpiceGroup");
                });

            modelBuilder.Entity("IndekserPrzypraw.Models.SpiceGroup", b =>
                {
                    b.HasOne("IndekserPrzypraw.Models.Drawer", "Drawer")
                        .WithMany("SpiceGroups")
                        .HasForeignKey("DrawerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drawer");
                });

            modelBuilder.Entity("IndekserPrzypraw.Models.Drawer", b =>
                {
                    b.Navigation("SpiceGroups");
                });

            modelBuilder.Entity("IndekserPrzypraw.Models.SpiceGroup", b =>
                {
                    b.Navigation("Spices");
                });

            modelBuilder.Entity("IndekserPrzypraw.Models.SpiceMixRecipe", b =>
                {
                    b.Navigation("Ingredients");
                });
#pragma warning restore 612, 618
        }
    }
}
