name: indekserprzypraw

services:
  database:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
  backend:
    # image: mrspaceman1/indekserprzypraw-backend:latest
    build: ./IndekserPrzypraw
    # ports:
    #   - 3001:80
    depends_on:
      - database
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      # - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
    command: command
  reverse_proxy_frontend:
    # image: mrspaceman1/indekserprzypraw-frontend:latest
    build: ./
    ports:
      - 80:80
      - 443:443
    # volumes:
    #   - ./nginx_certs:/etc/nginx/certs/
    depends_on:
      - backend
